### ISSUE TITLE
ImportError: No module named _winreg

### ISSUE THREAD

**Issue by xElkomy** [xnl-h4ck3r/GAP-Burp-Extension#11]
> There is issue with `ImportError: No module named _winreg` when try to install the `requirements.txt`,

- my jython version is the last 2.7.3

```cmd
java -jar C:/jython/jython.jar -m pip install -r ".\GAP-Burp-Extension\requirements.txt"
```

```py
Traceback (most recent call last):
  File "C:\jython\Lib\runpy.py", line 161, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\jython\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\jython\Lib\site-packages\pip\__main__.py", line 23, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "C:\jython\Lib\site-packages\pip\_internal\cli\main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\jython\Lib\site-packages\pip\_internal\cli\autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\jython\Lib\site-packages\pip\_internal\cli\main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "C:\jython\Lib\site-packages\pip\_internal\cli\cmdoptions.py", line 25, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
  File "C:\jython\Lib\site-packages\pip\_internal\cli\progress_bars.py", line 12, in <module>
    from pip._internal.utils.logging import get_indentation
  File "C:\jython\Lib\site-packages\pip\_internal\utils\logging.py", line 18, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "C:\jython\Lib\site-packages\pip\_internal\utils\misc.py", line 34, in <module>
    from pip._internal.locations import get_major_minor_version, site_packages, user_site
  File "C:\jython\Lib\site-packages\pip\_internal\locations.py", line 30, in <module>
    USER_CACHE_DIR = appdirs.user_cache_dir("pip")
  File "C:\jython\Lib\site-packages\pip\_internal\utils\appdirs.py", line 23, in user_cache_dir
    return _appdirs.user_cache_dir(appname, appauthor=False)
  File "C:\jython\Lib\site-packages\pip\_vendor\appdirs.py", line 300, in user_cache_dir
    path = os.path.normpath(_get_win_folder("CSIDL_LOCAL_APPDATA"))
  File "C:\jython\Lib\site-packages\pip\_vendor\appdirs.py", line 474, in _get_win_folder_from_registry
    import _winreg
ImportError: No module named _winreg
```

There is any help with this error beacuse the winreg module is used py CPython not jython.

**Comment by xElkomy** [comment]
I fixed it by download the standalone version and following the steps, Thanks
