### ISSUE TITLE
AssertionError on installing libraries

### ISSUE THREAD

**Issue by zyrgo** [xnl-h4ck3r/GAP-Burp-Extension#13]
Output of `java -jar jython-standalone-2.7.3.jar -m pip install -r requirements.txt`

```
DEPRECATION: pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.9.3-py2-none-any.whl (115 kB)
Collecting html5lib
  Using cached html5lib-1.1-py2.py3-none-any.whl (112 kB)
Collecting urllib3
  Using cached urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
Collecting soupsieve<2.0,>1.2; python_version < "3.0"
  Using cached soupsieve-1.9.6-py2.py3-none-any.whl (33 kB)
Collecting six>=1.9
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting webencodings
  Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: backports.functools-lru-cache; python_version < "3" in ./Lib/site-packages (from soupsieve<2.0,>1.2; python_version < "3.0"->beautifulsoup4->-r requirements.txt (line 1)) (1.6.4)
Installing collected packages: soupsieve, beautifulsoup4, six, webencodings, html5lib, urllib3
ERROR: Exception:
Traceback (most recent call last):
  File "/home/zyrgo/burp/Lib/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/home/zyrgo/burp/Lib/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/home/zyrgo/burp/Lib/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/home/zyrgo/burp/Lib/site-packages/pip/_internal/commands/install.py", line 395, in run
    installed = install_given_reqs(
  File "/home/zyrgo/burp/Lib/site-packages/pip/_internal/commands/install.py", line 395, in run
    installed = install_given_reqs(
  File "/home/zyrgo/burp/Lib/site-packages/pip/_internal/req/__init__.py", line 82, in install_given_reqs
    requirement.install(
  File "/home/zyrgo/burp/Lib/site-packages/pip/_internal/req/req_install.py", line 816, in install
    install_wheel(
  File "/home/zyrgo/burp/Lib/site-packages/pip/_internal/operations/install/wheel.py", line 837, in install_wheel
    _install_wheel(
  File "/home/zyrgo/burp/Lib/site-packages/pip/_internal/operations/install/wheel.py", line 719, in _install_wheel
    assert os.path.exists(pyc_path)
AssertionError
```

I have followed all the instructions correctly

**Comment by xnl-h4ck3r** [comment]
Hi @zyrgo, can you try updating pip with `python -m pip install -U pip` and try again?

**Comment by zyrgo** [comment]
Hey @xnl-h4ck3r , Updating didn't work, but I removed pip by deleting Lib and bin folder and again installed via ensurepip, now it's working fine.
Thank you

**Comment by xnl-h4ck3r** [comment]
Good to hear! Thanks for using GAP and good luck hunting for bugs!
