### ISSUE TITLE
Failed to load Python interpreter from Jython JAR file

### ISSUE THREAD

**Issue by bradsen** [xnl-h4ck3r/GAP-Burp-Extension#35]
Hi, I received the following error when installing the GAP extension in Burp Suite community edition.
 
java.lang.Exception: Failed to load Python interpreter from Jython JAR file
	at burp.Zd17.ZX(Unknown Source)
	at burp.Zns1.ZV(Unknown Source)
	at burp.Zuzc.Zi(Unknown Source)
	at burp.Zal.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)

**Comment by xnl-h4ck3r** [comment]
Hi @bradsen. That's not an issue with the extension, it sounds like a problem with your python environment in Burp. Go to the extension settings and check that you have the python environment set up correctly as per the instructions on the repo. Get the latest version of jython and try that.

**Comment by xnl-h4ck3r** [comment]
Hi @bradsen. I never heard back from you, so I will assume you manage to sort the problem and close this issue. If that isn't the case, then feel free to re-open the issue and let me know if you tried what I suggested. Thanks
